### ISSUE TITLE
Group creation

### ISSUE THREAD

**Issue by xamul-it** [xamul-it/group-buy#98]
Error 500 in groupo creation.

org.springframework.orm.hibernate5.HibernateOptimisticLockingFailureException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy[Proxy=1323971971; Query=update group_member set group_id=?, members_idx=? where id=?; Delegate=com.mysql.jdbc.JDBC4PreparedStatement@2b79cdda: update group_member set group_id=29, members_idx=0 where id=21]; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy[Proxy=1323971971; Query=update group_member set group_id=?, members_idx=? where id=?; Delegate=com.mysql.jdbc.JDBC4PreparedStatement@2b79cdda: update group_member set group_id=29, members_idx=0 where id=21]
        at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:287)

Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy[Proxy=1323971971; Query=update group_member set group_id=?, members_idx=? where id=?; Delegate=com.mysql.jdbc.JDBC4PreparedStatement@2b79cdda: update group_member set group_id=29, members_idx=0 where id=21]
        at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:67)

**Comment by xamul-it** [comment]
Nothing to fix. Works
